### ISSUE TITLE
Using your puzzle generator outside of the GUI

### ISSUE THREAD

**Issue by elydpg** [veroslav/sudoku-generator-solver-game#4]
Hello,

I found your sudoku puzzle generator, and I was wondering something. I am trying to generate arbitrary sized puzzles with varied difficulty, and I see that you have the tools to do this with your program. However, I am trying to get the result of the generation into an array within Java, as opposed to exporting it to file or PDF. How would I do this?

**Comment by veroslav** [comment]
Hi,

sure, you could use the generator in this way:

Generator gen = new ClassicGenerator(3, 20);
GeneratorResult result = gen.createNew(LogicSolver.Grading.EASY, Generator.Symmetry.NONE);
int[] puzzle = result.getGeneratedPuzzle();

**Comment by elydpg** [comment]
True, but how would I customize the difficulty and size parameters?

**Comment by elydpg** [comment]
Also, I tried to do this and it wouldn't let me put it in without method inputs. When I did add the inputs, this happened:

```
java.lang.ExceptionInInitializerError
    at com.matic.sudoku.solver.LogicSolver$Grading.<clinit>(LogicSolver.java:56)
    at Sudoku.<init>(Sudoku.java:141)
    at Sudoku.main(Sudoku.java:387)
```

I should point out here that Sudoku is my class where I'm running the code; not your Sudoku.class

```
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at edu.rice.cs.drjava.model.compiler.JavacCompiler.runCommand(JavacCompiler.java:272)
```

What's going on?

**Comment by veroslav** [comment]
I've modified my reply to show an example of how to set a difficulty and a symmetry. A quick look at your stacktrace indicates that the line 56 in LogicSolver is this one:
`EASY(Resources.getTranslation("puzzle.easy")),`
It appears to me that the translation resources can't be found, how are you running your program?

**Comment by elydpg** [comment]
what do you mean by "how" am I running your program?

**Comment by veroslav** [comment]
Are you running against my jar directly, what is the command line? How do you import my code?

**Comment by elydpg** [comment]
Ah. I'm running it directly from the source code. I'm not using the command line.

**Comment by elydpg** [comment]
Oh. Also I forgot to directly import Resources, however even when importing it the error is still thrown.

**Comment by veroslav** [comment]
Looks like you are missing the resources in the classpath. Hard to say without having more info, like where the different files reside on the disk and how you invoke your program (with java command).

**Comment by veroslav** [comment]
You could simply replace the call to `Resources.getTranslation()` into something like this:

`EASY("Easy")`

You might need to do this for every statement where the translations are used.

**Comment by elydpg** [comment]
Not just that. Anything that tries to use anything in resources class. Once I removed the translations, the random generation failed because it relied on the resources class.

Is it a problem that I'm removing the `com` folder out of the `src` folder?

**Comment by elydpg** [comment]
Ok so I kept the com folder inside the src folder, which required me to put my class inside. The ExceptionInInitializerErrors are gone but now I'm getting the following:

```
java.lang.NullPointerException
    at com.matic.sudoku.generator.ClassicGenerator.generateFilledBoard(ClassicGenerator.java:122)
    at com.matic.sudoku.generator.ClassicGenerator.createNew(ClassicGenerator.java:59)
    at Sudoku.<init>(Sudoku.java:137)
    at Sudoku.main(Sudoku.java:375)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at edu.rice.cs.drjava.model.compiler.JavacCompiler.runCommand(JavacCompiler.java:272)
```

In addition, A separate interactions pane is popping up whenever I ran your methods.

Perhaps I should send you my code so you can see how it's being implemented?
